# Generated by Django 5.2.11 on 2026-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_transaction_description_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='weekdays',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
