# Generated by Django 5.2.11 on 2026-02-20 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_recurringtransaction_weekdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('overspend', 'Overspending'), ('underspend', 'Underspending'), ('healthy', 'Healthy'), ('prediction', 'Prediction')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_month', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('predicted_expense', models.FloatField()),
                ('risk_level', models.CharField(choices=[('high', 'High Risk'), ('under', 'Under-utilizing'), ('healthy', 'Healthy'), ('insufficient', 'Insufficient Data')], default='insufficient', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
